#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE superset;
    CREATE DATABASE als_data;
    
    CREATE USER $GEMINI_POSTGRES_USER WITH PASSWORD '$GEMINI_POSTGRES_PASSWORD';
    GRANT CONNECT ON DATABASE als_data TO $GEMINI_POSTGRES_USER;
EOSQL

# Connect to als_data to grant table permissions
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "als_data" <<-EOSQL
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $GEMINI_POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $GEMINI_POSTGRES_USER;
EOSQL
