# Generated by Django 4.2.10 on 2024-02-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=255)),
                ('gene_name', models.CharField(max_length=255)),
                ('gene_risk_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('unique_protocol_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nct_id', models.CharField(max_length=255)),
                ('brief_title', models.TextField(blank=True, null=True)),
                ('study_type', models.CharField(blank=True, max_length=255, null=True)),
                ('study_phase', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=255, null=True)),
                ('study_submitance_date', models.DateField(blank=True, null=True)),
                ('study_submitance_date_qc', models.DateField(blank=True, null=True)),
                ('study_start_date', models.DateField(blank=True, null=True)),
                ('study_start_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status_verified_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('lead_sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_party_type', models.CharField(max_length=255, null=True)),
                ('responsible_party_investigator_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('collaborators', models.TextField(blank=True, null=True)),
                ('keyword', models.JSONField(blank=True, null=True)),
                ('intervention_name', models.JSONField(blank=True, null=True)),
                ('study_population', models.TextField(blank=True, null=True)),
                ('enrollment_count', models.IntegerField(blank=True, null=True)),
                ('enrollment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expanded_access', models.CharField(blank=True, choices=[('TRUE', 'True'), ('FALSE', 'False'), ('', '')], default='', max_length=5)),
                ('fda_regulated_drug', models.CharField(blank=True, choices=[('TRUE', 'True'), ('FALSE', 'False'), ('', '')], default='', max_length=5)),
                ('fda_regulated_device', models.CharField(blank=True, choices=[('TRUE', 'True'), ('FALSE', 'False'), ('', '')], default='', max_length=5)),
                ('clinical_trial_url', models.CharField(blank=True, max_length=255, null=True)),
                ('genes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
