# Generated by Django 4.2.10 on 2024-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='study_phase',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
