# Generated by Django 4.2.10 on 2024-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_trial_study_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='study_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
