# Generated by Django 4.2.10 on 2024-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_trial_study_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='other_outcomes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='primary_outcomes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='secondary_outcomes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
