# Generated by Django 4.2.10 on 2024-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_trial_other_outcomes_trial_primary_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='study_phase',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('Early Phase 1', 'Early Phase 1'), ('Phase 1', 'Phase 1'), ('Phase 1/2', 'Phase 1/2'), ('Phase 2', 'Phase 2'), ('Phase 2/3', 'Phase 2/3'), ('Phase 3', 'Phase 3')], default='NA', max_length=50),
        ),
    ]
