# Generated by Django 4.2.10 on 2024-02-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_trial_study_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='study_phase',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
