# Generated by Django 4.2.10 on 2024-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_trial_study_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Log',
            fields=[
                ('database_table_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('table_update_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
