# Generated by Django 4.2.10 on 2024-02-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_update_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='expanded_access',
        ),
    ]
