# Generated by Django 4.2.10 on 2024-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_remove_trial_expanded_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_healthy_volunteers',
            field=models.CharField(blank=True, choices=[('TRUE', 'True'), ('FALSE', 'False'), ('', '')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_max_age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_min_age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_standard_age',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
