# Generated by Django 4.2.10 on 2024-02-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_trial_eligibility_criteria_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='eligibility_criteria_max_age_years',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='eligibility_criteria_min_age_years',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
