# Generated by Django 4.2.10 on 2024-02-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_remove_trial_eligibility_criteria_standard_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_log',
            name='table_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
