# Generated by Django 4.2.10 on 2024-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_alter_update_log_table_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='eligibility_criteria_description',
            new_name='eligibility_criteria_generic_description',
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_exclusion_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria_inclusion_description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
