# Generated by Django 4.2.10 on 2024-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_rename_eligibility_criteria_description_trial_eligibility_criteria_generic_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='intervention_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
