# Generated by Django 4.2.10 on 2024-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_trial_intervention_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealeyTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=255)),
                ('overall_status', models.CharField(blank=True, max_length=255, null=True)),
                ('trial_contact_info', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('state_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
