# Generated by Django 4.2.10 on 2024-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_healeytrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healeytrial',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='healeytrial',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='healeytrial',
            name='state_abbreviation',
        ),
        migrations.AddField(
            model_name='healeytrial',
            name='geoPoint',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
