# Generated by Django 4.2.10 on 2024-03-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_remove_healeytrial_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healeytrial',
            old_name='city',
            new_name='enrollment_status',
        ),
        migrations.RemoveField(
            model_name='healeytrial',
            name='country',
        ),
        migrations.RemoveField(
            model_name='healeytrial',
            name='overall_status',
        ),
        migrations.RemoveField(
            model_name='healeytrial',
            name='zip_code',
        ),
    ]
