# Generated by Django 4.2.10 on 2024-03-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_rename_city_healeytrial_enrollment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healeytrial',
            name='geoPoint',
        ),
    ]
