# Generated by Django 4.2.10 on 2024-03-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_remove_healeytrial_geopoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=255)),
                ('intervention_description', models.TextField()),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='Dashboard.trial')),
            ],
        ),
    ]
