# Generated by Django 4.2.10 on 2026-01-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='related_genes',
            field=models.ManyToManyField(blank=True, related_name='trials', to='Dashboard.gene'),
        ),
    ]
