# Generated by Django 4.2.10 on 2026-01-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_trial_related_genes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='trials', to='Dashboard.trialstatus'),
        ),
    ]
