# Generated by Django 4.2.10 on 2026-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_trialstatus_trial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
