# Generated by Django 4.2.10 on 2026-01-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_trial_brief_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='intervention_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
