# Generated by Django 4.2.10 on 2026-01-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='related_genes',
            field=models.ManyToManyField(blank=True, related_name='news_articles', to='Dashboard.gene'),
        ),
    ]
