# Generated by Django 4.2.10 on 2026-01-21 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_alter_newsarticle_image_url_alter_newsarticle_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdb', 'PDB'), ('alphafold', 'AlphaFold'), ('custom', 'Custom URL')], max_length=20)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('assembly_id', models.CharField(blank=True, default='', max_length=32)),
                ('visual_style', models.CharField(blank=True, default='', max_length=64)),
                ('hide_controls', models.BooleanField(default=True)),
                ('alphafold_view', models.BooleanField(default=False)),
                ('custom_data_url', models.URLField(blank=True, default='')),
                ('custom_data_format', models.CharField(blank=True, default='cif', max_length=16)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='Dashboard.gene')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'external_id'], name='Dashboard_g_source__f56c8f_idx'), models.Index(fields=['gene', 'is_primary'], name='Dashboard_g_gene_id_321428_idx')],
            },
        ),
    ]
