# Generated by Django 4.2.10 on 2026-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_genestructure'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genestructure',
            name='Dashboard_g_source__f56c8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='genestructure',
            name='Dashboard_g_gene_id_321428_idx',
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='custom_data_format',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='custom_data_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='external_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='source_type',
            field=models.CharField(choices=[('pdb', 'PDB'), ('alphafold', 'AlphaFold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genestructure',
            name='visual_style',
            field=models.CharField(blank=True, default='cartoon', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='genestructure',
            unique_together={('gene', 'source_type', 'external_id')},
        ),
        migrations.RemoveField(
            model_name='genestructure',
            name='assembly_id',
        ),
    ]
